### ISSUE TITLE
cosmopy install failing

### ISSUE THREAD

**Issue by karthik340** [fetchai/cosmpy#238]
### Prerequisites

- [X] I am running the [latest CosmPy version](https://docs.fetch.ai/CosmPy/#version).
- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

should install with no error

### Current Behavior

ERROR: Failed building wheel for python-mbedtls 

### To Reproduce

pip3 install cosmpy

### Context

environment : Mac Air M1
python : 3.8.9
pip3 : 22.0.4

**Comment by 5A11** [comment]
This should be fixed after we cleaned up the dependencies in PR #242

**Comment by vincadian** [comment]
Its still not working
![image](https://user-images.githubusercontent.com/79286362/189759401-aeab0556-b720-486c-b1a4-0d2a441b2c9d.png)
